### ISSUE TITLE
Running the client

### ISSUE THREAD

**Issue by wfengk** [AskToni/asktoni-client#52]
Hey @RedTn @jrhender 

We were trying to add to the client and had some issues:

npm install

![npm_install](https://user-images.githubusercontent.com/8269985/37247998-dfab2102-247a-11e8-843d-3db7a25df33f.png)

npm run dev

![welcome_ _asktoni-client](https://user-images.githubusercontent.com/8269985/37248000-e58e1f34-247a-11e8-9dee-12ee3db468df.png)

Looks like it doesn't have the right version of webpack. When we install webpack version 4 it only introduces more dependency issues

Any thoughts?

**Comment by RedTn** [comment]
Issue has been fixed, try it again @wfengk

**Comment by jrhender** [comment]
I downgraded sinon-chai as well. After doing so, it works for me as well. Thanks Redmond.

**Comment by jrhender** [comment]
Commit with sinon-chai downgrade: https://github.com/AskToni/asktoni-client/commit/98a238846267453e7d905a7d05c37de757bc2ec5

**Comment by RedTn** [comment]
@jrhender Thanks!
Ya I added a package updating bot, which is pretty handy but I don't have enough test cases to safely commit the new versions, even though the build passes.
#YOLO
